import Router from './router';
import React, { useEffect, useState } from 'react';
import { useRecoilState } from 'recoil';
import { authenticated } from './store';
import axios from 'axios';


function App() {
	const [mounted, setMounted] = useState(false);
	const [auth, setAuth] = useRecoilState(authenticated);
	const getUser = async () => {
		try {
			let response = await axios.get('user');
			setAuth({
				check: true,
				user: response.data.data
			});
		} catch(err) {
			// 
		}

		setMounted(true);
	}

	useEffect(() => {
		getUser()
	}, [auth.check], mounted);

	if(!mounted) {
		return (
			<div className="justify-content-md-center align-items-center d-flex vh-100">
				<>
				{/*?xml version="1.0" encoding="utf-8"?*/}
				<svg
					xmlns="http://www.w3.org/2000/svg"
					xmlnsXlink="http://www.w3.org/1999/xlink"
					style={{
					margin: "auto",
					background: "none",
					display: "block",
					}}
					width="200px"
					height="200px"
				>
					<circle cx={50} cy={50} r={0} fill="none" stroke="#e90c59" strokeWidth={2}>
					<animate
						attributeName="r"
						repeatCount="indefinite"
						dur="1s"
						values="0;40"
						keyTimes="0;1"
						keySplines="0 0.2 0.8 1"
						calcMode="spline"
						begin="0s"
					/>
					<animate
						attributeName="opacity"
						repeatCount="indefinite"
						dur="1s"
						values="1;0"
						keyTimes="0;1"
						keySplines="0.2 0 0.8 1"
						calcMode="spline"
						begin="0s"
					/>
					</circle>
					<circle cx={50} cy={50} r={0} fill="none" stroke="#46dff0" strokeWidth={2}>
					<animate
						attributeName="r"
						repeatCount="indefinite"
						dur="1s"
						values="0;40"
						keyTimes="0;1"
						keySplines="0 0.2 0.8 1"
						calcMode="spline"
						begin="-0.5s"
					/>
					<animate
						attributeName="opacity"
						repeatCount="indefinite"
						dur="1s"
						values="1;0"
						keyTimes="0;1"
						keySplines="0.2 0 0.8 1"
						calcMode="spline"
						begin="-0.5s"
					/>
					</circle>
					{/* [ldio] generated by https://loading.io/ */}
				</svg>
</>
		
			</div>
		);
	}

	return <Router/>
}

export default App;